<?xml version="1.0" encoding="UTF-8"?>
<MobileElementEntity>
   <description></description>
   <name>p2</name>
   <tag></tag>
   <elementGuidId>00000000-0000-0000-0000-000000000000</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>clickable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>9a0ac515-a1b0-45f3-8041-2ed5ec3776c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>live-region</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>73c7f978-abc0-40d8-bdd7-36846d073a2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>window-id</name>
      <type>Main</type>
      <value>1065</value>
      <webElementGuid>6ac2a3c8-5471-438f-b7fd-c7c880bcc8e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>enabled</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>1f6c09b5-d3de-4045-a8bb-d8b2d1e082ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>screen-reader-focusable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>4a101285-a8d4-4fb3-9b4c-84725b5a0cd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>password</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>435471e4-7f0a-4b1d-a141-59d40b3250b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tooltip-text</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>87d2bea0-b6cd-4eac-9a8b-13f1c87ba290</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/j3.f1/android.view.View/android.view.View/android.view.View/i4.y/android.webkit.WebView/android.webkit.WebView/android.widget.TextView[2]</value>
      <webElementGuid>f31d8cff-d6bc-4f98-ac09-657f0a3db39b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>checked</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>9b4d7c80-13a0-4c4e-8f3b-5fd3053654e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>long-clickable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>7e5c93f1-b95a-4264-b9e2-f1aac26d3a58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>context-clickable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>eb4c18b8-303e-4e0a-a768-b1ff2c0f5cf0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Nama sungai Komering sendiri berasal dari nama seorang pedagang rempah-rempah (pinang) asal India. Pada masa Sriwijaya, daerah tersebut sedang ramai-ramainya mengadakan perdagangan pinang dengan India. Untuk mengumpulkan pinang didaerah itu, oleh pembeli dari India ditunjuklah seorang saudagar yang bertindak sebagai perwakilan perdagangan. Kebiasaan masyarakat setempat, menamai seseorang sesuai dengan tugas pekerjaannya. Kepada wakil pedagang dari India ini, masyarakat menamainya sesuai dengan asal yang bersangkutan, yaitu &quot;Komering Singh&quot;, yang berarti &quot;Juragan Pinang&quot;.</value>
      <webElementGuid>3472ef42-3754-4a96-9d2e-bb7dfc258ff2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>showing-hint</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>f93f7930-ed85-4783-b3d0-c8934f573af5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>a11y-important</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>d8d20dea-3562-4f22-a955-a8016cb8361a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>android.widget.TextView</value>
      <webElementGuid>59ebcf43-190e-4686-9b7f-55b1ac9eb925</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrollable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>811da81d-b771-4194-8e71-e9a23b7dba11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>9decc556-8cbe-4e64-81a9-4c60206f07f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>displayed</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>bda944f7-6148-4b16-9156-b73e094cb9bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>package</name>
      <type>Main</type>
      <value>id.sumsel.kaganga</value>
      <webElementGuid>90ebd4e1-65af-4121-a3ee-27d611ff1a99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>a11y-focused</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>e9b8fc3b-2ef5-4660-ba58-7bff9b124746</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>content-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>f76a8076-5492-4f39-a324-df3062fa6d18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dismissable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>6e61a804-3eb7-499b-861b-3e966ad9e148</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>checkable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>f6853273-be2c-42af-887a-678694624515</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>heading</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>a3950f1d-e61b-4fba-ad05-2aa3b4de1024</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>index</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>ffb86d55-09d2-47c3-9833-026a69a8bf0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>focusable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>f042f8aa-c077-4bda-b74b-95ee5fdf6b38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>hint</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>b7a57852-91fb-4f65-bba2-33f0934a61c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>focused</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>5ee7b8b3-d47a-42db-aeb9-b5c46a479f42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>bounds</name>
      <type>Main</type>
      <value>[81,936][999,2272]</value>
      <webElementGuid>70d7f85f-63d5-4170-8614-4b766950a652</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>drawing-order</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>6218cf4c-0c52-4c19-8221-ead7a53447c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text-entry-key</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>ba41d64e-2922-4c23-9f78-300d5c42fd0a</webElementGuid>
   </webElementProperties>
   <locatorCollection>
      <entry>
         <key>CUSTOM</key>
         <value></value>
      </entry>
      <entry>
         <key>ID</key>
         <value></value>
      </entry>
      <entry>
         <key>ANDROID_UI_AUTOMATOR</key>
         <value>new UiSelector().className(&quot;android.widget.TextView&quot;).text(&quot;Nama sungai Komering sendiri berasal dari nama seorang pedagang rempah-rempah (pinang) asal India. Pada masa Sriwijaya, daerah tersebut sedang ramai-ramainya mengadakan perdagangan pinang dengan India. Untuk mengumpulkan pinang didaerah itu, oleh pembeli dari India ditunjuklah seorang saudagar yang bertindak sebagai perwakilan perdagangan. Kebiasaan masyarakat setempat, menamai seseorang sesuai dengan tugas pekerjaannya. Kepada wakil pedagang dari India ini, masyarakat menamainya sesuai dengan asal yang bersangkutan, yaitu &quot;Komering Singh&quot;, yang berarti &quot;Juragan Pinang&quot;.&quot;)</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>CLASS_NAME</key>
         <value>android.widget.TextView</value>
      </entry>
      <entry>
         <key>ANDROID_VIEWTAG</key>
         <value></value>
      </entry>
      <entry>
         <key>ATTRIBUTES</key>
         <value>//*[@class = 'android.widget.TextView' and (@text = 'Nama sungai Komering sendiri berasal dari nama seorang pedagang rempah-rempah (pinang) asal India. Pada masa Sriwijaya, daerah tersebut sedang ramai-ramainya mengadakan perdagangan pinang dengan India. Untuk mengumpulkan pinang didaerah itu, oleh pembeli dari India ditunjuklah seorang saudagar yang bertindak sebagai perwakilan perdagangan. Kebiasaan masyarakat setempat, menamai seseorang sesuai dengan tugas pekerjaannya. Kepada wakil pedagang dari India ini, masyarakat menamainya sesuai dengan asal yang bersangkutan, yaitu &quot;Komering Singh&quot;, yang berarti &quot;Juragan Pinang&quot;.' or . = 'Nama sungai Komering sendiri berasal dari nama seorang pedagang rempah-rempah (pinang) asal India. Pada masa Sriwijaya, daerah tersebut sedang ramai-ramainya mengadakan perdagangan pinang dengan India. Untuk mengumpulkan pinang didaerah itu, oleh pembeli dari India ditunjuklah seorang saudagar yang bertindak sebagai perwakilan perdagangan. Kebiasaan masyarakat setempat, menamai seseorang sesuai dengan tugas pekerjaannya. Kepada wakil pedagang dari India ini, masyarakat menamainya sesuai dengan asal yang bersangkutan, yaitu &quot;Komering Singh&quot;, yang berarti &quot;Juragan Pinang&quot;.')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/j3.f1/android.view.View/android.view.View/android.view.View/i4.y/android.webkit.WebView/android.webkit.WebView/android.widget.TextView[2]</value>
      </entry>
      <entry>
         <key>ACCESSIBILITY</key>
         <value></value>
      </entry>
      <entry>
         <key>NAME</key>
         <value></value>
      </entry>
   </locatorCollection>
   <locatorStrategy>ATTRIBUTES</locatorStrategy>
   <platform>ANDROID</platform>
</MobileElementEntity>
